module.exports = ["JUDICIAL DISTRICT COURT",
"VERSUS",
"PARISH OF",
"ARREST NUMBER",
"undefined_11",
"1_3",
"2_3",
"Not prosecuted for any offense arising out of this charge_3",
"undefined_12",
"undefined_13",
"undefined_14",
"1_4",
"2_4",
"Conviction set asidedismissed",
"undefined_15",
"undefined_16",
"undefined_17",
"1_5",
"2_5",
"Conviction set asidedismissed_2",
"undefined_18",
"undefined_19",
"undefined_20",
"undefined_21",
"Conviction set asidedismissed_3",
"undefined_22",
"undefined_23",
"undefined_24",
"undefined_25",
"Conviction set asidedismissed_4",
"undefined_26",
"undefined_27",
"Attorney for MoverDefendant Name",
"Attorneys Bar Roll No",
"Address",
"City State ZIP Code",
"Telephone Number",
"MoverDefendant Name",
"Address_2",
"City State ZIP Code_2",
"Telephone Number_2",
"Check Box1",
"Check Box2",
"Check Box3",
"Check Box4",
"Check Box5",
"Check Box6",
"Check Box7",
"Check Box8",
"Check Box9",
"Check Box10",
"Check Box11",
"Check Box12",
"Check Box13",
"Check Box14",
"Check Box15",
"Check Box16",
"Check Box17",
"Check Box18",
"Check Box19",
"Check Box20",
"Check Box21",
"Check Box22",
"Check Box23",
"Check Box24",
"Check Box25",
"Check Box26",
"Check Box27",
"Check Box28",
"Check Box29",
"Check Box30",
"Check Box31",
"Check Box32",
"Check Box33",
"Check Box34",
"Check Box35",
"Check Box36",
"Check Box37",
"Check Box38",
"Check Box39",
"Check Box40",
"Check Box41",
"Check Box42",
"Check Box43",
"Check Box44",
"Check Box45",
"Check Box46",
"Check Box47",
"Check Box48",
"Check Box49",
"Check Box50",
"Check Box51",
"DIV",
"NO",
"Middle Initial",
"DOB",
"undefined",
"undefined_2",
"RACE",
"DRIVER LIC",
"ARRESTING AGENCY",
"1 Mover was arrested on",
"undefined_3",
"undefined_4",
"1",
"undefined_5",
"Not prosecuted for any offense arising out of this charge",
"undefined_6",
"1_2",
"undefined_8",
"2_2",
"Not prosecuted for any offense arising out of this charge_2",
"undefined_9",
"NAME",
"First Name",
"SSN last 4 digits XXXXX",
"SID if available",
"2",
"undefined_7",
"undefined_10",
"Text1",
"Text2",
"Check Box52",
"Check Box53"]